CREATE TABLE cars_class_d (
    Id SERIAL PRIMARY KEY,
    Class CHAR(1),
    "Order" INT,
    Brand VARCHAR(50),
    Model VARCHAR(50),
    Rarity VARCHAR(20),
    Stars INT,
    "Max Rank" INT,
    Epics INT,
    "Obtainable via" VARCHAR(50),
    "Garage Lv" INT,
    "Top Speed" FLOAT,
    Acceleration FLOAT,
    Handling FLOAT,
    Nitro FLOAT,
    "Nitro TS" FLOAT,
    "Perfect nitro TS" FLOAT,
    Added VARCHAR(50),
    "Added with" VARCHAR(50),
    "Added date" DATE,
    "Total upgrade cost" INT,
    "Total GL points" INT,
    Country VARCHAR(50),
    Tags VARCHAR(100),
    "BPs 1*" INT,
    "BPs 2*" INT,
    "BPs 3*" INT,
    "BPs 4*" INT,
    "BPs 5*" INT,
    "BPs 6*" INT,
    "Total BPs" INT,
    "Cost epic" INT
);